services:
  kedro:
    build: .
    image: wildbook-pipeline
    container_name: wildbook-pipeline
    volumes:
      - ./conf:/app/conf
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ../wbia-core/tests/test-dataset:/app/tests/test-dataset:ro
      - ./src:/app/src
      - ./tests:/app/tests/pipeline
    environment:
      - KEDRO_LOGGING_CONFIG=conf/base/logging.yml
      - HF_TOKEN=${HF_TOKEN}
    command: kedro run --pipeline identify
    networks:
      - wildbook-net

  docs:
    image: nginx:alpine
    container_name: wildbook-docs
    ports:
      - "4321:80"
    volumes:
      - ./docs:/usr/share/nginx/html:ro
    restart: unless-stopped

  viz:
    build:
      context: .
      dockerfile: Dockerfile.viz
    image: wildbook-viz
    container_name: wildbook-viz
    ports:
      - "4141:4141"
    volumes:
      - ./conf:/app/conf
      - ./data:/app/data
      - ./src:/app/src
    command: kedro viz run --host 0.0.0.0 --port 4141

networks:
  wildbook-net:
    external: true
    name: wildbook-network
